api = "0.2"

[buildpack]
  id = "paketo-buildpacks/puma"
  name = "Paketo Puma Buildpack"
  homepage = "https://github.com/paketo-buildpacks/puma"

[metadata]
  include-files = ["bin/build","bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

