api = "0.7"

[buildpack]
  description = "A buildpack for starting a puma server for a Ruby app"
  homepage = "https://github.com/paketo-buildpacks/puma"
  id = "paketo-buildpacks/puma"
  keywords = ["ruby", "puma"]
  name = "Paketo Buildpack for Puma"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/puma/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "*"

[[targets.distros]]
name = "ubuntu"
version = "18.04"

[[targets.distros]]
name = "ubuntu"
version = "22.04"
