api = "0.2"

[buildpack]
  id = "paketo-community/puma"
  name = "Paketo Puma Buildpack"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  include_files = ["bin/build","bin/detect", "bin/run", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
